import main
printf

ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve but for funnnnnn，
codemoreoutsideinsteadofpingpingfullno，
ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve
