import main
printf(
ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve but for funnnnnn
codemoreoutsideinsteadofpingpingfullno1111
ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve
)
