import main
printf

ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve but for funnnnnn，
codemoreoutsideinsteadofpingpingfull，
ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve

void codemoreoutsideinsteadofpingpingfull{string []}
class codemoreoutsideinsteadofpingpingfull
switch(){
  in case ForTestNoReasonAllThatWeNeedButEnjoyEverythingWeHaveAndDeserve,
else codemoreoutsideinsteadofpingpingfull
}
